name: flutter_pkg
description: DOCUMENT VERIFICATION SDK.
version: 0.0.1
homepage:

environment:
  sdk: ">=2.16.2 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  camera: ^0.10.3+2
  device_info_plus: ^8.1.0
  flutter:
    sdk: flutter
  get: ^4.6.5
  google_mlkit_face_detection: ^0.5.0
  google_mlkit_image_labeling: ^0.5.0
  image: ^4.0.15
  # image_cropper: ^3.0.1
  image_picker: ^0.8.6
  path_provider: ^2.0.11
  sensors_plus: ^2.0.0
  shared_preferences: ^2.0.17
  tflite: ^1.1.2
  flutter_screenutil: ^5.6.1
 
  # tflite_flutter: ^0.9.0
  # tflite_flutter_helper: ^0.2.1
  vibration: ^1.7.6
  cached_network_image: ^3.2.3
  flutter_native_screenshot: ^1.1.2
  permission_handler: ^10.2.0
  another_flushbar: ^1.12.29
  google_mlkit_text_recognition: any
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  assets: 
    - packages/flutter_pkg/assets/Selfie.png
    - packages/flutter_pkg/assets/Blink.png
    - packages/flutter_pkg/assets/app_icon.jpg
    - packages/flutter_pkg/assets/image 10.png
    - packages/flutter_pkg/assets/image 13-2.png
    - packages/flutter_pkg/assets/image 16.png
    - packages/flutter_pkg/assets/front.png
    - packages/flutter_pkg/assets/back.png
    - packages/flutter_pkg/assets/ID card.png
    - packages/flutter_pkg/assets/box.png
    - packages/flutter_pkg/assets/front_new/model_unquant.tflite
    - packages/flutter_pkg/assets/front_new/labels.txt
    - packages/flutter_pkg/assets/back/labels.txt
    - packages/flutter_pkg/assets/back/model_unquant.tflite
    - packages/flutter_pkg/assets/tilted/labels.txt
    - packages/flutter_pkg/assets/tilted/model_unquant.tflite
    - packages/flutter_pkg/assets/Mobile Frame.png
    - packages/flutter_pkg/assets/instructions.png
    - packages/flutter_pkg/assets/camera_button_active.webp
    - packages/flutter_pkg/assets/camera_button_inactive.webp
    - packages/flutter_pkg/assets/camera_frame_active.webp
    - packages/flutter_pkg/assets/camera_frame_inactive.webp
    - packages/flutter_pkg/assets/front_new/1model_unquant.tflite
    - packages/flutter_pkg/assets/tilted/1model_unquant.tflite
    - packages/flutter_pkg/assets/Frame.png
    - packages/flutter_pkg/assets/Frame-2.png
    - packages/flutter_pkg/assets/Frame-3.png
    - packages/flutter_pkg/assets/Frame-4.png
  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
